### PR TITLE
Dep versions

### PR DESCRIPTION
**Pull request by FrankReh**
Found the dependencies could be brought up to latest with minimal effort.

If you accept these, assume you will use squash. If you want any changes or me to resubmit with a squashed version, that's no problem.

### CODE REVIEW

**Comment by FrankReh** [comment]
From this, I have also got a version that compiles against the wasmtime* 20.0.0 versions and the wit* 0.205.0 versions, but the changes necessary were a little more than trivial so  the current commits could be reviewed first (if the repo is even meant to keep up).

**Review by rylev — APPROVED** [review]
Looks great! Thanks! I'd be happy to take a look at a version that upgrades to wasmtime 20 if you're interested. Otherwise, I'll merge as is.

**Comment by FrankReh** [comment]
Was waiting for my other PR to be merged before merging from main and then pushing the wasmtime 20 support changes.

**Comment by rylev** [comment]
@FrankReh I apologize for letting this sit for so long. I've opened and merged https://github.com/rylev/wepl/pull/24 which updates to wasmtime 22. I'm going to close this issue. I appreciate your help here though!

**Pull request closed without merging**
